### PR TITLE
upgrade xml DTD to 4.5

### PR DESCRIPTION
**Pull request by kloczek**
Trival change which upgardes xml DTD version to latest stable 4.5.

### CODE REVIEW

**Comment by kloczek** [comment]
BTW looking on https://github.com/gssapi/gssproxy/compare/v0.9.1...main I think that it would be good to flush all already committed changes as new release.

**Comment by kloczek** [comment]
Gentle ping .. any chance to merge this PR? 🤔

**Comment by simo5** [comment]
Very sorry, I wanted to pull this in 0.9.2 and then missed it.

**Comment by kloczek** [comment]
I've asked because I would like to delete forked repo 😋 
Thank you 👍 😄

**Pull request merged**
